# Generated by Django 6.1.1 on 2026-09-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaservicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categoriaservicio',
            name='nombre',
            field=models.CharField(unique=True),
        ),
    ]
