# Generated by Django 6.1.1 on 2026-10-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_categoriaservicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaservicio',
            options={'verbose_name': 'Categoría de Servicio', 'verbose_name_plural': 'Categorías de Servicio'},
        ),
    ]
